### ISSUE TITLE
Off^n

### ISSUE THREAD

**Issue by steakknife** [gitterHQ/readme-badger#30] opened 2016-10-12 06:15 UTC
Places a Gitter tag inside build instructions. 😢

**Comment by MadLittleMods** [comment] 2016-10-12 12:56
@steakknife Can you provide the commit by the badger that does the wrong thing?

**Comment by chinesedfan** [comment] 2018-04-01 11:52
If there already had some badges, hope #44 can help you.

**Comment by MadLittleMods** [comment] 2018-04-17 05:53
Closing because we don't have a reproduction commit and #44 may help

**Closed by MadLittleMods** 2018-04-17 05:53 UTC
