### ISSUE TITLE
Too easy to make accidental pull requests

### ISSUE THREAD

**Issue by stain** [gitterHQ/readme-badger#24] opened 2016-01-25 11:29 UTC
As the *Create a room for a repository* screen keeps changing its size while it is loading the repository list (at least in Firefox 43.0), it is way too easy to just accidentally select the totally wrong repository from the wrong organization, which immediately seems to add a README pull request there, and then make both the user and gitter.im look like spammers.
 
Could an actual button (or a confirmation pop-up) be used before adding the pull request? A big green **Create room** button would do - instead of doing it on single-click on a repository.

**Comment by MadLittleMods** [comment] 2016-01-25 14:47
Duplicate of https://github.com/gitterHQ/gitter/issues/698

The confirmation will also help with showing that it will create a pull request.

**Closed by MadLittleMods** 2016-01-25 14:47 UTC
